import { Header } from '@/components/Header';
import { SmoothScroll } from '@/components/ui/smooth-scroll';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SmoothScroll>
          <Header />

          <main className='min-h-screen w-screen bg-black'>{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}
