import { Header } from '@/components/Header';
import { SmoothScroll } from '@/components/ui/smooth-scroll';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer } from '@/components/Footer';
import { Cursor } from '@/components/Cursor';
import { PageTransition } from '@/components/PageTransition';
import { Preloader } from '@/components/Preloader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Cursor />
        <Preloader />
        <Header />

        <SmoothScroll>
          <main className='min-h-screen w-screen bg-black'>
            <PageTransition />

            {children}
          </main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
